#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later

mount -t proc     none /proc
mount -t sysfs    none /sys
mount -t devtmpfs none /dev
mount -t tmpfs    none /tmp
mount -t tmpfs    none /run

mdev -s

[ -c /dev/null ]    || mknod -m 666 /dev/null    c 1 3
[ -c /dev/console ] || mknod -m 600 /dev/console c 5 1
[ -c /dev/tty ]     || mknod -m 666 /dev/tty     c 5 0

trap 'echo ""; sync; halt -f'     USR1
trap 'echo ""; sync; poweroff -f' USR2
trap 'echo ""; sync; reboot -f'   TERM

echo ""
echo "+-----------------------------------------+"
echo "|        Zevory Linux - bootstrap OK      |"
echo "+-----------------------------------------+"
echo ""
echo "[zevory] kernel : $(uname -r)"
echo "[zevory] arch   : $(uname -m)"
echo "[zevory] uptime : $(cut -d. -f1 /proc/uptime)s"
echo ""

echo "[zevory] bootstrap OK, shell ready" > /dev/kmsg 2>/dev/null

dmesg -n 4

while true; do

    setsid -c /bin/sh -c 'exec /bin/sh </dev/console >/dev/console 2>/dev/console' \
        </dev/console >/dev/console 2>/dev/console &
    wait "$!"
    echo ""
    echo "[zevory] shell died, restarting..."
    echo ""
    sleep 1
done

