timeout: 5
interface_branding: Zevory Linux


/Zevory Linux Bootstrap
    protocol: linux
    path: boot():/boot/zevory/vmlinuz
    cmdline: init=/init console=ttyS0,115200 console=tty0
    module_path: boot():/boot/zevory/initramfs.cpio.zst


#  Finally works!!!! After like 200 fixes, it works. If I touch anything related to Limine again, I’m dropping the project. I do not want to deal with Limine ever again :(